<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>DYF Scrum Manager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="<?php echo $this->asset('assets/css/bootstrap.css') ?>" rel="stylesheet">
    <link href="<?php echo $this->asset('assets/css/layout.css') ?>" rel="stylesheet">
	<link href="<?php echo $this->asset('assets/css/joint.css') ?>" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>
	<script src="<?php echo $this->asset('app/joint.js') ?>"></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBarHead(); ?>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="index.php">DYF Scrum Manager</a>
          <ul class="nav">
            <li class="active"><a href="index.php">Accueil</a></li>
              <?php if(isset($_SESSION['islogged']) && $_SESSION['islogged'] == true)
            echo '<li class="dropdown">
              <a href="properties.php?type=showall" class="dropdown-toggle" data-toggle="dropdown">
                Projet
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="index.php?action=projet">Créer un Projet</a></li>
                <li><a href="index.php?action=affiche_projet">Afficher mes projets</a></li>
            </ul>';
            ?>
          </li>            
          </ul>
          <ul class="nav pull-right">
            <li class="dropdown">
              <a href="properties.php?type=showall" class="dropdown-toggle" data-toggle="dropdown">
                <?php if(isset($_SESSION['islogged']) && $_SESSION['islogged'] == true)
                        echo "Connecté en tant que <u>".$_SESSION['pseudo']."</u>";
                      else
                      echo "Compte";
?>

                <b class="caret"></b>
              </a>
              
            <ul class="dropdown-menu">
              <?php if(isset($_SESSION['islogged']) && $_SESSION['islogged'] == true){
                      echo '<li><a href ="index.php?action=pageperso">Mon Compte</a></li>';
                      echo '<li><a href ="index.php?action=deconnexion">Deconnexion</a></li>';
                    }
                    else
                      echo "<li><a href='index.php?action=login'>Connexion</a></li>";  
					  
              ?>     
            </ul>
            
          </li>
          
        </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <?php if (count($this['flash_messages'])): ?>
        <?php foreach ($this['flash_messages'] as $label => $messages): ?>
          <?php foreach ($messages as $message): ?>
            <div class="alert alert-<?php echo $label ?>"><?php echo $message ?></li>
          <?php endforeach; ?>
        <?php endforeach; ?>
      <?php endif ?>
    
      <div id="content">
        <?php echo $contentForLayout; ?>
      </div>
    </div>
    <?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBar(); ?>
  </body>
</html>
