<ul class="nav nav-pills">
  <li >
    <?php echo '<a href="index.php?action=affiche_projet_num&id_projet='.$id_projet.'">Information</a>' ?>
  </li>
  <li>   
    <?php echo '<a href="index.php?action=ajout-utilisateur&id_projet='.$id_projet.'">Collaborateurs</a>' ?>
  </li>
  <li>
   <?php echo '<a href="index.php?action=sprints&id_projet='.$id_projet.'">Sprint</a>' ?>
 </li>
 <li>
   <?php echo '<a href="index.php?action=backlog&id_projet='.$id_projet.'">Backlog</a>' ?>
 </li>
 <li class="active">
   <?php echo '<a href="index.php?action=affiche_kanban&id_projet='.$id_projet.'">Kanban</a>' ?>
 </li>
</ul>
<h1>Kanban</h1>

<?php 


$result0 = $conn->query("SELECT * FROM SPRINT WHERE ID_PROJET = ".$id_projet." ORDER BY DATE_DEB");
if ($result0->num_rows > 0) {
  $i = 1;
  echo '<div class="accordion" id="accordion2">';
  while($row0 = $result0->fetch_assoc()) {
    if($i == 1){
    echo '<div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse'.$i.'">
        Sprint #'.$i.'
      </a>
    </div>
    <div id="collapse'.$i.'" class="accordion-body collapse in">
      <div class="accordion-inner">';}
    else{
      echo '<div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse'.$i.'">
        Sprint #'.$i.'
      </a>
    </div>
    <div id="collapse'.$i.'" class="accordion-body collapse">
      <div class="accordion-inner">';
    }


    $result = $conn->query("SELECT UTILISATEUR.ID, UTILISATEUR.NOM, UTILISATEUR.PRENOM FROM UTILISATEUR JOIN PARTICIPER ON PARTICIPER.ID_UTILISATEUR = UTILISATEUR.ID WHERE PARTICIPER.ID_PROJET = ".$id_projet);

    echo '<table class="table table-striped table-bordered table-hover" align="center"><thead><tr><th>Collaborateur</th><th>A FAIRE</th><th>EN COURS</th><th>FAIT</th></thead><tbody>';
    while($row = $result->fetch_assoc()) {
      echo '<tr><td>'.utf8_encode($row["PRENOM"]).' '.utf8_encode($row["NOM"]).'</td>';

      $result2 = $conn->query("SELECT ID FROM ETAT");
      while($row2 = $result2->fetch_assoc()){
        echo '<td>';
        echo '<table class="table" align="center"><tbody>';

        $result3 = $conn->query("SELECT TACHE.ID, TACHE.INTITULE FROM TACHE JOIN ETAT ON ETAT.ID = TACHE.ID_ETAT JOIN KANBAN ON TACHE.ID = KANBAN.ID_TACHE JOIN UTILISATEUR ON UTILISATEUR.ID = KANBAN.ID_UTILISATEUR JOIN ASSOCIER ON ASSOCIER.ID_TACHE = TACHE.ID JOIN USER_STORY ON USER_STORY.ID = ASSOCIER.ID_USER_STORY JOIN BACKLOG ON BACKLOG.ID_USER_STORY = USER_STORY.ID JOIN PROJET ON PROJET.ID = BACKLOG.ID_PROJET JOIN CONTENIR ON CONTENIR.ID_USER_STORY = USER_STORY.ID WHERE CONTENIR.ID_SPRINT = ".$row0['ID']." AND PROJET.ID = ".$id_projet." AND UTILISATEUR.ID = ".$row['ID']." AND TACHE.ID_ETAT = ".$row2['ID']);
        while($row3 = $result3->fetch_assoc()){
          echo "<tr><td>".$row3['INTITULE'];
          if($row2['ID'] != 3 && $row['ID'] == $_SESSION['id']){
          echo '<a href="#myModal" role="button" class="btn btn-mini" data-toggle="modal">>></a>
 
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 id="myModalLabel">Changement d\'état</h3>
</div>
<div class="modal-body">
<form name="input" action="index.php?action=verif_changer_etat_tache&id_projet='.$id_projet.'" method="post">
<p>Êtes-vous sûr de vouloir changer l\'état de cette tâche?</p>
</div>
<div class="modal-footer">
<input type="hidden" name="id_tache" value="'.$row3['ID'].'"/>
<input type="hidden" name="id_etat" value="'.$row2['ID'].'"/>
<button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
<input class="btn btn-primary" type="submit"></input>
 </form>
</div>
</div> ';}
          echo "</td></tr>";
        }
        echo '</tbody></table></td>';
      }
      echo '</tr>';
    }
    echo '</tbody></table>';
    echo '</div>
    </div>
    </div>';
    $i = $i + 1;
  }
  echo '</div>';
}
?>

