<ul class="nav nav-pills">
  <li class="active">
    <?php echo '<a href="index.php?action=affiche_projet_num&id_projet='.$id_projet.'">Information</a>' ?>
  </li>
  <li>   
    <?php echo '<a href="index.php?action=ajout-utilisateur&id_projet='.$id_projet.'">Collaborateurs</a>' ?>
  </li>
   <li>
   <?php echo '<a href="index.php?action=sprints&id_projet='.$id_projet.'">Sprint</a>' ?>
   </li>
  <li>
   <?php echo '<a href="index.php?action=backlog&id_projet='.$id_projet.'">Backlog</a>' ?>
   </li>
    <li>
   <?php echo '<a href="index.php?action=affiche_kanban&id_projet='.$id_projet.'">Kanban</a>' ?>
 </li>
  <li>
   <?php echo '<a href="index.php?action=affiche_tests&id_projet='.$id_projet.'">Tests</a>' ?>
 </li>
  <li>
    <?php echo '<a href="index.php?action=github&id_projet='.$id_projet.'">Github</a>' ?>
  </li>
     <li>
    <?php echo '<a href="index.php?action=burndown_chart&id_projet='.$id_projet.'">Burndown Chart</a>' ?>
  </li>
</ul>

<?php
  $result = $conn->query("SELECT * FROM PROJET WHERE PROJET.ID = ".$id_projet);
  $row = $result->fetch_assoc();
  echo "<h1>Projet ".$row["NOM"]."</h1>";
  echo "<h2>Description</h2>";
  echo "<div class='well well-large'>".utf8_encode($row["DESCRIPTION"])."</div>";
  echo "<h2>Lien GIT</h2>    
  <div class='alert alert-success'><a href=".$row["LIEN_GIT"].">".$row["LIEN_GIT"]."</a></div>";
?>
