<ul class="nav nav-pills">
  <li >
    <?php echo '<a href="index.php?action=affiche_projet_num&id_projet='.$id_projet.'">Information</a>' ?>
  </li>
  <li>   
    <?php echo '<a href="index.php?action=ajout-utilisateur&id_projet='.$id_projet.'">Collaborateurs</a>' ?>
  </li>
  <li class="active">
   <?php echo '<a href="index.php?action=backlog&id_projet='.$id_projet.'">Backlog</a>' ?>
</ul>
 
<h1>Backlog du projet</h1>

<h2>User Story</h2>



<?php echo '<p><a class="btn btn-large btn-primary" href="index.php?action=form_us&id_projet='.$id_projet.'">Créer une User Story &raquo;</a></p>'; ?>
