<form class="form-horizontal" name="inscription" method="post" action="index.php?action=verif_inscription" onSubmit="return verifFormulaire()">
<fieldset>

<!-- Inscription -->
<legend>Inscription</legend>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="nom">Nom</label>
  <div class="controls">
    <input id="nom" name="nom" placeholder="Nom" class="input-xlarge" required="" type="text">
    <p class="help-block">Entrez votre nom.</p>
  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="prenom">Prénom</label>
  <div class="controls">
    <input id="prenom" name="prenom" placeholder="Prénom" class="input-xlarge" required="" type="text">
    <p class="help-block">Entrez votre prénom.</p>
  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="mail">Adresse Email</label>
  <div class="controls">
    <input id="mail" name="mail" placeholder="Email" class="input-xlarge" required="" type="text">
    <p class="help-block">Entrez votre adresse email.</p>
  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="login">Login</label>
  <div class="controls">
    <input id="login" name="login" placeholder="Login" onKeyUp="verifPseudo(this.value)" class="input-xlarge" required="" type="text"><div id="pseudobox"></div>
    <p class="help-block">Entrez votre login. (15 caractères maximum)</p>
  </div>
</div>

<!-- Password input-->
<div class="control-group">
  <label class="control-label" for="mdp">Mot de passe</label>
  <div class="controls">
    <input id="mdp" name="mdp" placeholder="Mot de passe" class="input-xlarge" required="" type="password">
    <p class="help-block">Entrez votre mot de passe. (20 caractères maximum)</p>
  </div>
</div>

<!-- Button (Double) -->
<div class="control-group">
  <label class="control-label" for="return"></label>
  <div class="controls">
    <button type="submit" id="submit" name="submit" class="btn btn-success">S'inscrire</button>
    <button id="return" name="return" class="btn btn-default">Annuler</button>
  </div>
</div>

</fieldset>
</form>

