<?php $lien = "index.php?action=verif_modif_sprint&id_projet=".$id_projet."&id_sprint=".$id_sprint;
echo '<form class="form-horizontal" name="form_sprint" method="post" action='.$lien.'>';

?>
	<fieldset>
				<legend>Modifier le sprint</legend>		
		<div class="control-group">
			<label class="control-label" for="type_user">Date début</label>
			<div class="controls">
				<input type="date" id="date_deb" name="date_deb" placeholder="début" class="input-xlarge" required="">
				
			</div>
		</div>		
		<div class="control-group">
			<label class="control-label" for="but">Date fin</label>
			<div class="controls">
				<input type="date" id="date_fin" name="date_fin" placeholder="fin" class="input-xlarge" required="" type="text">				
			</div>
		</div>		
		<div class="control-group">
			<label class="control-label" for="return"></label>
			<div class="controls">
			<button type="submit" id="submit" name="submit" class="btn btn-success">Créer</button>			
			</div>
		</div>
	</fieldset>
</form>