
<ul class="nav nav-pills">
  <li>
    <?php echo '<a href="index.php?action=affiche_projet_num&id_projet='.$id_projet.'">Information</a>' ?>
  </li>
  <li>   
    <?php echo '<a href="index.php?action=ajout-utilisateur&id_projet='.$id_projet.'">Collaborateurs</a>' ?>
  </li>
  <li>
    <li class="active">
   <?php echo '<a href="index.php?action=sprints&id_projet='.$id_projet.'">Sprint</a>' ?>
   </li>
   <li>
   <?php echo '<a href="index.php?action=backlog&id_projet='.$id_projet.'">Backlog</a>' ?>
 </li>
  <li>
   <?php echo '<a href="index.php?action=affiche_kanban&id_projet='.$id_projet.'">Kanban</a>' ?>
 </li>
  <li>
   <?php echo '<a href="index.php?action=affiche_tests&id_projet='.$id_projet.'">Tests</a>' ?>
 </li>
  <li>
    <?php echo '<a href="index.php?action=github&id_projet='.$id_projet.'">Github</a>' ?>
  </li>
</ul>

 <div class="container-fluid">
 	 <div class="span10">
<?php 

$result0 = $conn->query("SELECT * FROM SPRINT WHERE ID_PROJET = ".$id_projet." AND SPRINT.DATE_DEB<= CURDATE() AND SPRINT.DATE_FIN >= CURDATE()");
if ($result0->num_rows > 0) {
	$row = $result0->fetch_assoc();
  	echo '<h1>Sprint actuel </h1>';
 	$dd = substr ( $row['DATE_DEB'] , 8 ,2 );
 	$md = substr ( $row['DATE_DEB'] , 5 ,2 );
	$yd = substr ( $row['DATE_DEB'] , 0, 4 );
	$df = substr ( $row['DATE_FIN'] , 8 ,2 );
 	$mf = substr ( $row['DATE_FIN'] , 5 ,2 );
	$yf = substr ( $row['DATE_FIN'] , 0, 4 );
	echo '<div class="hero-unit">';
  	echo "<p class='lead'>N°".$row['ID']."<em> du ".$dd."/".$md."/".$yd." au ".$df."/".$mf."/".$yf."</em></p>";
  	$result01 = $conn->query("SELECT USER_STORY.* FROM USER_STORY JOIN CONTENIR ON CONTENIR.ID_USER_STORY = USER_STORY.ID WHERE CONTENIR.ID_SPRINT =".$row['ID']);
  	if($result01->num_rows > 0){
  	 echo '<table class="table table-striped table-bordered table-hover">';
  	 echo '<thead><tr><th>N°</th><th>Intitulé</th><th>Coût</th><th>Priorité</th></tr></thead>';
  	 echo '<tbody>';
  		while($row2 = $result01->fetch_assoc()){
        if(empty($row2['BENEFICE']))
          echo "<tr><td>".$row2['ID']."</td><td>En tant que ".utf8_encode($row2['TYPE_UTILISATEUR']).", je souhaite ".utf8_encode($row2['BUT']).".</td><td>".$row2['COUT']."</td><td>".$row2["PRIORITE"]."</td></td>";
        else
  			 echo "<tr><td>".$row2['ID']."</td><td>En tant que ".utf8_encode($row2['TYPE_UTILISATEUR']).", je souhaite ".utf8_encode($row2['BUT'])." afin ".utf8_encode($row2['BENEFICE']).".</td><td>".$row2['COUT']."</td><td>".$row2["PRIORITE"]."</td></td>";
  		}
    echo '</tbody></table>';
    echo '</div>';
	}
}
echo '</div> <div class="span10">';

echo "<h1>Sprints du projet</h1>";

$result1 = $conn->query("SELECT SPRINT.* FROM SPRINT WHERE SPRINT.ID_PROJET = ".$id_projet." ORDER BY DATE_DEB");
if ($result1->num_rows > 0) {
  $i = 1;
  echo '<div class="accordion" id="accordion2">';
  while($row1 = $result1->fetch_assoc()) {
    if($i == 1){
    $dd = substr ( $row1['DATE_DEB'] , 8 ,2 );
 	$md = substr ( $row1['DATE_DEB'] , 5 ,2 );
	$yd = substr ( $row1['DATE_DEB'] , 0, 4 );
	$df = substr ( $row1['DATE_FIN'] , 8 ,2 );
 	$mf = substr ( $row1['DATE_FIN'] , 5 ,2 );
	$yf = substr ( $row1['DATE_FIN'] , 0, 4 );
    echo '<div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseSprint'.$row1['ID'].'">
        <div>Sprint #'.$row1['ID'].' du '.$dd.'/'.$md.'/'.$yd.' au '.$df.'/'.$mf.'/'.$yf.'</div>
      </a>
    </div>
    <div id="collapseSprint'.$row1['ID'].'" class="accordion-body collapse in">
      <div class="accordion-inner">';
  	}
    else{
    	$dd = substr ( $row1['DATE_DEB'] , 8 ,2 );
 	$md = substr ( $row1['DATE_DEB'] , 5 ,2 );
	$yd = substr ( $row1['DATE_DEB'] , 0, 4 );
	$df = substr ( $row1['DATE_FIN'] , 8 ,2 );
 	$mf = substr ( $row1['DATE_FIN'] , 5 ,2 );
	$yf = substr ( $row1['DATE_FIN'] , 0, 4 );
      echo '<div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseSprint'.$row1['ID'].'">
        <div>Sprint #'.$row1['ID'].' du '.$dd.'/'.$md.'/'.$yd.' au '.$df.'/'.$mf.'/'.$yf.'</div>
      </a>
    </div>
    <div id="collapseSprint'.$row1['ID'].'" class="accordion-body collapse">
      <div class="accordion-inner">';
    }
    $i = $i + 1;

    $result2 = $conn->query("SELECT USER_STORY.* FROM USER_STORY JOIN CONTENIR ON USER_STORY.ID = CONTENIR.ID_USER_STORY WHERE CONTENIR.ID_SPRINT = ".$row1['ID']);
if ($result2->num_rows > 0) {
  $i = 1;
  echo '<div class="accordion" id="accordionUS2'.$row1['ID'].'">';
  while($row0 = $result2->fetch_assoc()) {
    if($i == 1){
      if(!empty($row0['BENEFICE'])){
        echo '<div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionUS2'.$row1['ID'].'" href="#collapseUS'.$row0['ID'].'">
        <div><div class="pull-left">US #'.$row0['ID'].' &nbsp;</div> En tant que '.utf8_encode($row0['TYPE_UTILISATEUR']).', je souhaite '.utf8_encode($row0['BUT']).' afin '.utf8_encode($row0['BENEFICE']).' <div class="pull-right">'.$row0['COUT'].' points | priorité : '.$row0['PRIORITE'].'</div></div>
      </a>
    </div>
    <div id="collapseUS'.$row0['ID'].'" class="accordion-body collapse in">
      <div class="accordion-inner">';}
      else{
        echo '<div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionUS2'.$row1['ID'].'" href="#collapseUS'.$row0['ID'].'">
        <div><div class="pull-left">US #'.$row0['ID'].' &nbsp;</div> En tant que '.utf8_encode($row0['TYPE_UTILISATEUR']).', je souhaite '.utf8_encode($row0['BUT']).' <div class="pull-right">'.$row0['COUT'].' points | priorité : '.$row0['PRIORITE'].'</div></div>
      </a>
    </div>
    <div id="collapseUS'.$row0['ID'].'" class="accordion-body collapse in">
      <div class="accordion-inner">';}}
    else{
      if(!empty($row0['BENEFICE'])){
      echo '<div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionUS2'.$row1['ID'].'" href="#collapseUS'.$row0['ID'].'">
        <div><div class="pull-left">US #'.$row0['ID'].' &nbsp;</div> En tant que '.utf8_encode($row0['TYPE_UTILISATEUR']).', je souhaite '.utf8_encode($row0['BUT']).' afin '.utf8_encode($row0['BENEFICE']).' <div class="pull-right">'.$row0['COUT'].' points | priorité : '.$row0['PRIORITE'].' </div></div>      </a>
    </div>
    <div id="collapseUS'.$row0['ID'].'" class="accordion-body collapse">
      <div class="accordion-inner">';}
      else{
         echo '<div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionUS2'.$row1['ID'].'" href="#collapseUS'.$row0['ID'].'">
        <div><div class="pull-left">US #'.$row0['ID'].' &nbsp;</div> En tant que '.utf8_encode($row0['TYPE_UTILISATEUR']).', je souhaite '.utf8_encode($row0['BUT']).' <div class="pull-right">'.$row0['COUT'].' points | priorité : '.$row0['PRIORITE'].' </div></div>      </a>
    </div>
   <div id="collapseUS'.$row0['ID'].'" class="accordion-body collapse">
      <div class="accordion-inner">';}
      }



    $result = $conn->query("SELECT TACHE.* FROM TACHE JOIN ASSOCIER ON ASSOCIER.ID_TACHE = TACHE.ID WHERE ASSOCIER.ID_USER_STORY = ".$row0['ID']);

    echo '<ul class="thumbnails">';
    while($row = $result->fetch_assoc()) {
         echo '<li class="span2">
                  <div class="thumbnail" style="width: 160px; height: 160px;">

                    <form name="input" action="index.php?action=modifier_tache&id_projet='.$id_projet.'" method="post">
                                      <input type="hidden" name="id_tache" value="'.$row['ID'].'"/>
<input type="image" src="'.Atomik::asset('assets/images/glyphicons/glyphicons_030_pencil.png').'" width="15" height="15" alt="Submit form"></input><div class="pull-right"><p>'.$row['COUT'].'</p></div>
</form>

                    <h5 style="text-align:center;">'.utf8_encode($row['INTITULE']).'</h5>
                    <p style="text-align:center;">'.utf8_encode($row['DESCRIPTION']).'</p>';
                    if($row['ID_ETAT'] == 1){
                      echo '<p style="text-align:center;" class="text-warning">À faire</p>';
                    }
                    else if($row['ID_ETAT'] == 1){
                      echo '<p style="text-align:center;" class="text-info">En cours</p>';
                    }
                    else
                    {
                      echo '<p style="text-align:center;" class="text-success">Terminée</p>';
                    }

                  echo '<div class="pull-right"><a href="#myModalTache'.$row['ID'].'" role="button" class="btn btn-link btn-mini" data-toggle="modal"> <img src="'.Atomik::asset('assets/images/glyphicons/glyphicons_016_bin.png').'" width="15" height="15" alt="" href=#></a></div>
 
          <div id="myModalTache'.$row['ID'].'" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Suppression de tache</h3>
          </div>
          <div class="modal-body">
          <form name="input" action="index.php?action=supp_tache&id_projet='.$id_projet.'" method="post">
          <p>Êtes-vous sûr de vouloir supprimer cette tâche?</p>
          </div>
          <div class="modal-footer">
          <input type="hidden" name="id_tache" value="'.$row['ID'].'"/>
          <button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
          <input class="btn btn-primary" type="submit"></input>
           </form>
          </div>
          </div></div>
                </li>';
    }
    echo '</ul>';
    echo '<p style="text-align:center;" ><a href="index.php?action=form_tache&id_projet='.$id_projet.'&id_us='.$row0['ID'].'"><img src="'.Atomik::asset('assets/images/glyphicons/glyphicons_190_circle_plus.png').'" class="img-circle"></a></p>';
    echo '<a href="#myModalUSsuppr'.$row0['ID'].'" role="button" class="btn btn-link btn-mini" data-toggle="modal"> <img src="'.Atomik::asset('assets/images/glyphicons/glyphicons_016_bin.png').'" width="15" height="15" alt="" href=#></a>
 
          <div id="myModalUSsuppr'.$row0['ID'].'" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Suppression de User Story</h3>
          </div>
          <div class="modal-body">
          <form name="input" action="index.php?action=supprimer_us&id_projet='.$id_projet.'" method="post">
          <p>Êtes-vous sûr de vouloir supprimer cette User Story?</p>
          </div>
          <div class="modal-footer">
          <input type="hidden" name="id_us" value="'.$row0['ID'].'"/>
          <button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
          <input class="btn btn-primary" type="submit"></input>
           </form>
          </div>
          </div>

          <a href="#myModalUSModif'.$row0['ID'].'" role="button" class="btn btn-link btn-mini" data-toggle="modal"> <img src="'.Atomik::asset('assets/images/glyphicons/glyphicons_030_pencil.png').'" width="15" height="15" alt="" href=#></a>
 
          <div id="myModalUSModif'.$row0['ID'].'" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Modification de User Story</h3>
          </div>
          <div class="modal-body">
          <form name="input" action="index.php?action=modifier_us&id_projet='.$id_projet.'" method="post">
          <p>Êtes-vous sûr de vouloir modifier cette User Story?</p>
          </div>
          <div class="modal-footer">
          <input type="hidden" name="id_us" value="'.$row0['ID'].'"/>
          <button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
          <input class="btn btn-primary" type="submit"></input>
           </form>
          </div>
          </div>
    </div>
    </div></div>';
    $i = $i + 1;
  }
  echo '</div>';
}

	echo '</div></div></div>';
    }
	echo "</div>";
}
    


?>


		<div class="btn-toolbar" style="margin: 0;">
			<div class="btn-group">
				<?php echo '<a class="btn btn-primary" href="index.php?action=ajouter_sprint&id_projet='.$id_projet.'">';?>
					Ajouter sprint
				</a>
			</div>
			<div class="btn-group">
				<a class="btn btn-warning dropdown-toggle" data-toggle="dropdown" href="#">
					Modifier sprint
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<?php
						$qry = "SELECT SPRINT.ID, SPRINT.DATE_DEB, SPRINT.DATE_FIN FROM SPRINT WHERE ID_PROJET = ".$id_projet;
						$r = $conn->query($qry);
						if ($r == FALSE)
							echo '<div class="alert alert-danger" role="alert">Error 33: Bad request.</div>';
						else
						{
							$i=1;
							while($rw2 = $r->fetch_assoc()) {
								echo '<li ><a href="index.php?action=modifier_sprint&id_sprint='.$rw2["ID"].'&id_projet='.$id_projet.'"><b>Sprint '.$i.'</b> du '.$rw2["DATE_DEB"].' au '.$rw2["DATE_FIN"].'</a></li>';
								$i++;
							}
						}
					?>
				</ul>
			</div>
			<div class="btn-group">
				<a class="btn btn-danger dropdown-toggle" data-toggle="dropdown" href="#">
					Supprimer sprint
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<?php
						$q = "SELECT SPRINT.ID, SPRINT.DATE_DEB, SPRINT.DATE_FIN FROM SPRINT WHERE ID_PROJET = ".$id_projet;
						$rep = $conn->query($q);
						if ($rep == FALSE)
							echo '<div class="alert alert-danger" role="alert">Error 33: Bad request.</div>';
						else
						{
							$i=1;
							while($rw3 = $rep->fetch_assoc()) {
								echo '<li><a href="index.php?action=supprimer_sprint&id_sprint='.$rw3["ID"].'&id_projet='.$id_projet.'"><b>Sprint '.$i.'</b> du '.$rw3["DATE_DEB"].' au '.$rw3["DATE_FIN"].'</a></li>';
								$i++;
							}
						}
					?>
				</ul>
			</div>
			</div>
		</div>
		 <div class="span10">
		<h2>User Story par sprint</h2>
		
		<?php 
		$query = "SELECT USER_STORY.*, CONTENIR.ID_SPRINT FROM USER_STORY JOIN BACKLOG ON USER_STORY.ID = BACKLOG.ID_USER_STORY LEFT JOIN CONTENIR ON CONTENIR.ID_USER_STORY = USER_STORY.ID WHERE BACKLOG.ID_PROJET = ".$id_projet;
		$result = $conn->query($query);
		if($result == FALSE)
			echo '<div class="alert alert-danger" role="alert">Error 33: Bad request.</div>';
		else
		{
			echo '<div class="panel panel-default">';
			echo '<table class="table" align="center"><thead><tr><th>N°</th><th>En tant que</th><th>Je souhaite </th><th>Afin de </th><th>Cout</th><th>Priorite</th><th>Sprint</th><th>Associer</th></tr></thead><tbody>';
			while($row = $result->fetch_assoc()) {
        echo '<tr><td>'.utf8_encode($row["ID"]).'</td>';
				echo '<td>'.utf8_encode($row["TYPE_UTILISATEUR"]).'</td>';
				echo '<td>'.utf8_encode($row["BUT"]).'</td>';
				echo '<td>'.utf8_encode($row["BENEFICE"]).'</td>';
				echo '<td>'.utf8_encode($row["COUT"]).'</td>';
				echo '<td>'.utf8_encode($row["PRIORITE"]).'</td>';
				echo '<td>'.utf8_encode($row["ID_SPRINT"]).'</td>';
				echo '<td><div class="btn-group"><button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown">';
				echo 'Choisir sprint<span class="caret"></span></button>';
				echo '<ul class="dropdown-menu" role="menu">';
				$query2 = "SELECT SPRINT.ID, SPRINT.DATE_DEB, SPRINT.DATE_FIN FROM SPRINT WHERE ID_PROJET = ".$id_projet;
				$result2 = $conn->query($query2);
				if ($result2 == FALSE)
					echo '<div class="alert alert-danger" role="alert">Error 33: Bad request.</div>';
				else
				{
					$i=1;
					while($row2 = $result2->fetch_assoc()) {
						echo '<li><a href="index.php?action=ajout_user_story_sprint&id_sprint='.$row2["ID"].'&id_us='.$row["ID"].'&id_projet='.$id_projet.'"><b>Sprint '.$row2['ID'].'</b> du '.$row2["DATE_DEB"].' au '.$row2["DATE_FIN"].'</a></li>';
						$i++;
					}
				}
				echo '</ul></td></tr>';
			}
			echo '</tbody></table></div>';
		}
		?>
	</div>
</div>
