
 <div class="page-header"><h3>Liste de tache </h3></div>
    <div class="container">     
        <div class="row"> 
        <div class="col-xs-12 col-sm-10 col-md-6"> 
            <table class="table table-bordered table-striped table-hover"> 
               
          <thead> 
          <tr> 
          <td>TACHE</td> 
           <td>DESCRIPTION</td>                
          
          <td></td>
          <td></td>
          </tr> 
          </thead> 
    <?php
    
     while($row = $resul->fetch_assoc()){

      ?>
      <tbody>
        <tr>
           <form method="post" action ="index.php?action=supp">
            <td><p><?php echo $row['INTITULE']; ?></p></td>
           <td><p><?php echo $row['DESCRIPTION']; ?></p></td>
              
          <?php echo " <td> <input type='checkbox' name='id_rep[]'  value='".$row['ID']."' > </td>"; ?>             

      <td><button type="submit" id="del" name="delete" onclick="return confirm('Voulez-vous supprimer cette tache')"class="btn btn-danger">del</button></td>
      <td><button type="submit" id="update" name="update" class="btn btn-success">Update</button></td>
           </form>
                   
        </tr>

    <?php
   
     }

    
?>